<?php

class ZenAiAssistPluginScaffolder
{
    public function scaffold(string $projectRoot, string $uniqueKey, string $version = 'v1.0.0', array $options = []): array
    {
        $normalizedKey = $this->normalizeKey($uniqueKey);
        if ($normalizedKey === '') {
            return [
                'ok' => false,
                'message' => 'Plugin key must contain letters or numbers.',
                'normalized_key' => $normalizedKey,
                'files' => [],
            ];
        }

        $version = trim($version);
        if ($version === '') {
            $version = 'v1.0.0';
        }

        $projectRoot = rtrim($projectRoot, '/\\') . '/';
        $pluginRoot = $projectRoot . 'zc_plugins/' . $normalizedKey . '/' . $version . '/';
        if (file_exists($pluginRoot)) {
            return [
                'ok' => false,
                'message' => 'Target plugin directory already exists.',
                'plugin_root' => $pluginRoot,
                'normalized_key' => $normalizedKey,
                'files' => [],
            ];
        }

        $displayName = trim((string)($options['name'] ?? ''));
        if ($displayName === '') {
            $displayName = $this->displayName($normalizedKey);
        }

        $author = trim((string)($options['author'] ?? ''));
        if ($author === '') {
            $author = 'Your Name';
        }

        $description = trim((string)($options['description'] ?? ''));
        if ($description === '') {
            $description = 'Encapsulated Zen Cart plugin scaffold generated by Zen AI Assist.';
        }

        $directories = [
            $pluginRoot . 'Installer/languages/english/',
            $pluginRoot . 'catalog/includes/classes/',
            $pluginRoot . 'catalog/includes/languages/english/',
            $pluginRoot . 'catalog/includes/modules/pages/',
            $pluginRoot . 'catalog/includes/templates/template_default/',
            $pluginRoot . 'admin/includes/classes/',
            $pluginRoot . 'admin/includes/languages/english/extra_definitions/',
            $pluginRoot . 'resources/guidance/',
            $pluginRoot . 'resources/skills/',
        ];

        foreach ($directories as $directory) {
            if (!is_dir($directory) && !mkdir($directory, 0775, true) && !is_dir($directory)) {
                return [
                    'ok' => false,
                    'message' => 'Failed to create scaffold directories.',
                    'plugin_root' => $pluginRoot,
                    'normalized_key' => $normalizedKey,
                    'files' => [],
                ];
            }
        }

        $files = [
            $pluginRoot . 'manifest.php' => $this->manifestContents($version, $displayName, $description, $author),
            $pluginRoot . 'filenames.php' => $this->filenamesContents($normalizedKey),
            $pluginRoot . 'Installer/ScriptedInstaller.php' => $this->installerContents(),
            $pluginRoot . 'Installer/languages/english/main.php' => $this->installerLanguageContents(),
            $pluginRoot . 'resources/skills/catalog.json' => $this->skillCatalogContents($displayName),
            $pluginRoot . 'resources/skills/plugin-workflow.md' => $this->skillContents($displayName),
            $pluginRoot . 'README.md' => $this->readmeContents($displayName, $normalizedKey, $version),
        ];

        $createdFiles = [];
        foreach ($files as $path => $contents) {
            file_put_contents($path, $contents);
            $createdFiles[] = $path;
        }

        return [
            'ok' => true,
            'message' => 'Plugin scaffold created.',
            'plugin_root' => $pluginRoot,
            'normalized_key' => $normalizedKey,
            'files' => $createdFiles,
        ];
    }

    private function normalizeKey(string $value): string
    {
        $value = strtolower(trim($value));
        $value = preg_replace('/[^a-z0-9]+/', '-', $value) ?? '';

        return trim($value, '-');
    }

    private function displayName(string $key): string
    {
        $pieces = preg_split('/[-_]+/', $key) ?: [$key];
        $pieces = array_map(static fn(string $piece): string => ucfirst($piece), $pieces);

        return implode(' ', $pieces);
    }

    private function manifestContents(string $version, string $displayName, string $description, string $author): string
    {
        return <<<PHP
<?php

return [
    'pluginVersion' => '{$this->escapePhpString($version)}',
    'pluginName' => '{$this->escapePhpString($displayName)}',
    'pluginDescription' => '{$this->escapePhpString($description)}',
    'pluginAuthor' => '{$this->escapePhpString($author)}',
    'pluginId' => 0,
    'zcVersions' => [],
    'changelog' => '',
    'github_repo' => '',
    'pluginGroups' => [],
];
PHP;
    }

    private function installerContents(): string
    {
        return <<<PHP
<?php

use Zencart\PluginSupport\ScriptedInstaller as ScriptedInstallBase;

class ScriptedInstaller extends ScriptedInstallBase
{
    protected function executeInstall()
    {
        return true;
    }

    protected function executeUninstall()
    {
        return true;
    }
}
PHP;
    }

    private function filenamesContents(string $key): string
    {
        $constant = 'FILENAME_' . strtoupper(str_replace('-', '_', $key));

        return <<<PHP
<?php

define('{$constant}', '{$key}');
PHP;
    }

    private function installerLanguageContents(): string
    {
        return <<<PHP
<?php

return [
];
PHP;
    }

    private function readmeContents(string $displayName, string $key, string $version): string
    {
        return <<<MD
# {$displayName}

Scaffolded by Zen AI Assist.

## Plugin Root

`zc_plugins/{$key}/{$version}/`

## Next Steps

- update `manifest.php` with the real plugin metadata
- add or adjust `filenames.php` constants for any new pages
- add installer behavior in `Installer/ScriptedInstaller.php`
- add catalog or admin files under the encapsulated plugin directories
- expand `resources/skills/` with task-specific agent workflows for the plugin
- install the plugin through Zen Cart Plugin Manager before testing runtime behavior
MD;
    }

    private function skillContents(string $displayName): string
    {
        return <<<MD
# {$displayName} Plugin Workflow

Use this skill when working on the {$displayName} plugin.

## Checklist

- inspect `manifest.php`, `Installer/`, and `filenames.php` first
- keep catalog pages aligned across `header_php.php`, language files, and templates
- add admin menu definitions for admin entrypoints
- validate install state through Plugin Manager before debugging runtime behavior
MD;
    }

    private function skillCatalogContents(string $displayName): string
    {
        $title = $this->escapeJsonString($displayName . ' Plugin Workflow');
        $summary = $this->escapeJsonString('Guide agent work on the ' . $displayName . ' plugin using the normal Zen Cart plugin structure and lifecycle.');
        $intent = $this->escapeJsonString('Keep plugin work inside the encapsulated plugin boundaries and validate the baseline plugin files first.');

        return <<<JSON
{
  "skills": [
    {
      "id": "plugin-workflow",
      "title": "{$title}",
      "summary": "{$summary}",
      "intent": "{$intent}",
      "tags": ["plugin", "workflow"],
      "when_to_use": [
        "Working on the {$title}.",
        "Creating or expanding plugin structure."
      ],
      "required_context": [
        "Plugin root",
        "Target feature area"
      ],
      "source_refs": [
        "manifest.php",
        "Installer/ScriptedInstaller.php",
        "filenames.php"
      ],
      "workflow_steps": [
        "Inspect manifest.php, Installer/, and filenames.php first.",
        "Keep catalog and admin work inside the plugin version directory.",
        "Install the plugin through Plugin Manager before debugging runtime behavior."
      ],
      "validation_steps": [
        "Confirm manifest.php exists.",
        "Confirm Installer/ScriptedInstaller.php exists."
      ],
      "anti_patterns": [
        "Do not edit core bootstrap files when plugin integration points are sufficient."
      ],
      "expected_outputs": [
        "baseline plugin metadata",
        "repeatable plugin workflow"
      ],
      "validation_rules": [
        {
          "type": "path_exists",
          "root": "plugin",
          "path": "manifest.php",
          "description": "Plugin manifest exists."
        },
        {
          "type": "path_exists",
          "root": "plugin",
          "path": "Installer/ScriptedInstaller.php",
          "description": "Plugin installer exists."
        }
      ],
      "content_file": "plugin-workflow.md"
    }
  ]
}
JSON;
    }

    private function escapePhpString(string $value): string
    {
        return str_replace(['\\', '\''], ['\\\\', '\\\''], $value);
    }

    private function escapeJsonString(string $value): string
    {
        return addcslashes($value, "\\\"\n\r\t/");
    }
}
